### PR TITLE
Add QAT configuration section name as a parameter

### PR DESCRIPTION
**Pull request by ipuustin**
Do not mandate that the QAT Driver configuration file section is called `[SHIM]`, but instead let the user configure the desired name. Keep [SHIM] as the default configuration section name. This functionality is useful in containerized environments, where the container has to access only a certain accelerator (with the corresponding configuration).

### CODE REVIEW

**Comment by Yogaraj-Alamenda** [comment]
Hi @ipuustin Thanks for your support. The pull request will go through internal process and will be merged in the next release.

**Comment by Yogaraj-Alamenda** [comment]
Hi @ipuustin 
 As a part of internal code review and testing, Is it OK to change the following ?
1. Change the env variable to "QAT_ENGINE_SECTION_NAME" as it is specific to QAT Engine use.
2. secure_getenv() is available from glibc 2.17 onwards so for earlier versions we will use get_env()
3. Addressing minor internal code review comments like initialization of variables, add WARN messages, etc wherever needed.

**Comment by ipuustin** [comment]
Hi @Yogaraj-Alamenda !

The first change is in my opinion not ok, because the Kubernetes QAT device plugin uses this variable for telling containers about the QAT section which to use (the device plugin PR is here: https://github.com/intel/intel-device-plugins-for-kubernetes/pull/164). This makes the environment variable not specific to the OpenSSL QAT Engine -- the device plugin is using it also for QAT software which is not using the QAT Engine, such as compression acceleration and other TLS stacks.

The second and third changes are fine. Thanks!

**Comment by ipuustin** [comment]
@Yogaraj-Alamenda Do you want me to do the changes or do you want to change the patch? I don't see the "internal code review comments" so I can't help much with them.

**Comment by Yogaraj-Alamenda** [comment]
Hi @ipuustin 
The changes are done and merged in the internal branch. It should be available in Github with the next release.

**Comment by stevelinsell** [comment]
Thankyou! Merged into Release v0.5.41

**Pull request closed without merging**
